networks:
  proxy:
    external: true

services:
  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material:latest
    networks:
      - proxy
    volumes:
      - ./config:/docs
    environment:
      PUID: 1000
      PGID: 1000
      SITE_NAME: "Nick Conway's Homelab"
      SITE_URL: https://homelab.conway.dev
      REPO_URL: https://github.com/nickconway/homelab
      HOMEPAGE: https://homelab.conway.dev
      LOGO: https://conway.dev/favicon.png
      FAVICON: https://conway.dev/favicon.png
      GITHUB_LINK: https://github.com/nickconway
      MASTODON_LINK: https://mastodon.social/@nickconway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkdocs.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.mkdocs.rule=Host(`homelab.conway.dev`)"
      - "traefik.http.routers.mkdocs.tls=true"
      - "traefik.http.routers.mkdocs.tls.certresolver=prod"
      - "traefik.http.services.mkdocs.loadbalancer.server.port=8000"
    restart: unless-stopped
