networks:
  proxy:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.4.0@sha256:91e963bfda569ba115206e843febb446f473ab525add4e08b2b9e3beffa16985
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York    # optional: set desired timezone
    volumes:
      - ./data/app:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.uptime-kuma.rule=Host(`${SERVICE_SUBDOMAIN:-uptime}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    restart: unless-stopped
    networks:
      - proxy

  autokuma:
    image: ghcr.io/bigboot/autokuma:2.0.0@sha256:8acbd3ad3ec8cb6c066aa0ee541154921283ec78159015937128541921c47974
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://uptime-kuma:3001
      AUTOKUMA__KUMA__USERNAME: ${UPTIME_USERNAME}
      AUTOKUMA__KUMA__PASSWORD: ${UPTIME_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/auto:/data
      - ./data/auto/config.toml:/root/.config/autokuma/config.toml
    networks:
      - proxy
    depends_on:
      - uptime-kuma
