networks:
  proxy:
    external: true
  paperless:
    driver: bridge
    name: paperless

services:
  paperless-redis:
    image: docker.io/library/redis:8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data/redis:/data
    networks:
      - paperless

  paperless-postgres:
    image: docker.io/library/postgres:18.3@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
    networks:
      - paperless

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:3.0.4@sha256:3838b9a4260d23acc5bb63aed407138435e70b56e5806f4baa350ca184e57582
    restart: unless-stopped
    depends_on:
      - paperless-postgres
      - paperless-redis
      - paperless-gotenberg
      - paperless-tika
    # ports:
    #   - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/app:/usr/src/paperless/data
      - ./data/media:/usr/src/paperless/media
      - ./data/export:/usr/src/paperless/export
      - ./data/consume:/usr/src/paperless/consume
      - ./data/scripts:/scripts
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-postgres
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: ${PAPERLESS_SOCIALACCOUNT_PROVIDERS}
      PAPERLESS_POST_CONSUME_SCRIPT: /scripts/post
      PAPERLESS_FILENAME_FORMAT: '{correspondent}/{created_year}/{created_month}/{created_day}/{title}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.paperless.rule=Host(`${SERVICE_SUBDOMAIN:-docs}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    networks:
      - proxy
      - paperless

  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:8.35.0@sha256:a16a14e1f18a71405624bc028e90d4ef50ea774c352b303639c10bf7b141f760
    restart: unless-stopped

    environment:
      PUID: 1000
      PGID: 1000
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless

  paperless-tika:
    image: apache/tika:3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    networks:
      - paperless
