networks:
  proxy:
    external: true

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:10.23.0@sha256:9f9205cfc20368bd9a4152f7708a9e7626525d8f4eadb1a25e5079708c5c4304
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.cyberchef.rule=Host(`${SERVICE_SUBDOMAIN:-cyberchef}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.cyberchef.tls=true"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=80"
    restart: unless-stopped
