networks:
  proxy:
    external: true

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:11.2.0@sha256:f829c2f358153b6b0ce5c226d97851e8728719d1e02e682bf7210d40663e93f9
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.cyberchef.rule=Host(`${SERVICE_SUBDOMAIN:-cyberchef}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.cyberchef.tls=true"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=80"
    restart: unless-stopped
