networks:
  proxy:
    external: true

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.cyberchef.rule=Host(`cyberchef.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.cyberchef.tls=true"
      - "traefik.http.routers.cyberchef.tls.certresolver=prod"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=80"
    restart: unless-stopped
