networks:
  proxy:
    external: true

services:
  deemix:
    image: ghcr.io/bambanah/deemix:v4.5.1@sha256:367a03f070a163fb41129b7f7717a2dbaa611eca6c767194f77bd0575b1b7e79
    networks:
      - proxy
    volumes:
      - ./data/downloads:/downloads
      - ./data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - DEEMIX_SINGLE_USER=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deemix.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.deemix.rule=Host(`${SERVICE_SUBDOMAIN:-deemix}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.deemix.tls=true"
      - "traefik.http.services.deemix.loadbalancer.server.port=6595"
    restart: unless-stopped
