networks:
    mc:
      ipam:
        config:
          - subnet: 10.0.250.0/24
    proxy:
        external: true

services:
  mc:
    image: itzg/minecraft-server:2026.9.2@sha256:de5d1b1a83eba576f6c8a688fac2a3523ce457724cdebc8ea48d7818b74cdf6e
    environment:
      TYPE: PAPER
      EULA: "true"
      ONLINE_MODE: FALSE
    volumes:
      - ./data/server:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      mc:
        ipv4_address: 10.0.250.2

  mc-router:
    image: itzg/mc-router:1.47.2@sha256:64ae69eaa7a6800a79bbf962f027f4020878efa25183359115bc7f6ee569c36e
    restart: unless-stopped
    ports:
        - "25565:25565"
    networks:
      mc:
        ipv4_address: 10.0.250.3
      proxy:
    volumes:
        - ./data/router/config.json:/config.json
    environment:
        ROUTES_CONFIG: /config.json
        ROUTES_CONFIG_WATCH: true
    command:
        - -trusted-proxies=127.0.0.1/32,10.0.0.0/8,172.16.0.0/12
        - -receive-proxy-protocol
        - -use-proxy-protocol

  mc-proxy:
    image: itzg/mc-proxy:2026.10.0@sha256:ad35279fe06ec23ad0a2b8980894490177c6121eefb8784e5e5d8912aa6cbc07
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Powered by Docker
      REPLACE_ENV_VARIABLES: "true"
    volumes:
      - ./data/proxy/config.yml:/config/config.yml
      - ./data/proxy/server:/server
    networks:
        mc:
            ipv4_address: 10.0.250.4

  playit:
    image: ghcr.io/playit-cloud/playit-agent:1.0.10@sha256:ca4766ced6e5bcee19137337808ec8fee5867c0910ac737efbb0bb452c378521
    networks:
      mc:
        ipv4_address: 10.0.250.5
    environment:
        - SECRET_KEY=${SECRET_KEY}
