services:
  ollama:
    image: ollama/ollama:0.32.4@sha256:10c13eb515db310990527d36ca14a136da4bcc0fbf2bf3b15e9c1f111e9d3cd4
    ports:
      - 11434:11434
    volumes:
      - ./data:/root/.ollama
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
    runtime: nvidia
