services:
  ollama:
    image: ollama/ollama:0.20.7@sha256:487324a9312240e3e122446f351b1f1e3f68d884ef854c246db2e08792440d94
    ports:
      - 11434:11434
    volumes:
      - ./data:/root/.ollama
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
    runtime: nvidia
