services:
  ollama:
    image: ollama/ollama:0.32.0@sha256:57f573b47f1f71ebb445789f279fe3e596a8beab182f7cf486db9205bad87c5a
    ports:
      - 11434:11434
    volumes:
      - ./data:/root/.ollama
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
    runtime: nvidia
