services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./data:/root/.ollama
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
    runtime: nvidia
