#!/bin/bash
set -euo pipefail

docker build . --tag git."${SERVICES_BASE_DOMAIN}"/"$GITEA_USER"/crowdsec-dashboard:latest

docker push -a git."${SERVICES_BASE_DOMAIN}"/"$GITEA_USER"/crowdsec-dashboard
