FROM metabase/metabase:v0.63.1.8@sha256:64afaf99949f2b4d7f367d1ec20636ec8bbf52aa929e70bf57818ff8bc3f5d0e

RUN mkdir /data/ && wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -d /data/
