FROM metabase/metabase:v0.62.4.4@sha256:8dddca0f6d77ffb647b080b00fb50348ed62b222c63a9a45d6c12812815db6b3

RUN mkdir /data/ && wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -d /data/
