FROM metabase/metabase:v0.63.1.12@sha256:4f150effd4849b89c428bc98fc1df300792fbc3a3567cc5697e0daa6c13d8ff0

RUN mkdir /data/ && wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -d /data/
