networks:
  proxy:
    external: true

services:
  stirling-pdf:
    image: frooodle/s-pdf:2.14.1-fat@sha256:e09e109a19ff2538b11176932a724766d07ad11ba63b6c25e8e25e12f1cc5235
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: true
      LANGS: en_US
    volumes:
      - ./data/tesseract:/usr/share/tessdata
      - ./data/configs:/configs
      - ./data/custom-files:/customFiles/
      - ./data/logs:/logs/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.stirling-pdf.rule=Host(`${SERVICE_SUBDOMAIN:-pdfs}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.stirling-pdf.tls=true"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
    restart: unless-stopped
