networks:
  proxy:
    external: true

services:
  stirling-pdf:
    image: frooodle/s-pdf:3.0.0-fat@sha256:b0387d124f86ab095db6579f90cd5209a340ff216d12f85ed0beeef2ed6ae19c
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: true
      LANGS: en_US
    volumes:
      - ./data/tesseract:/usr/share/tessdata
      - ./data/configs:/configs
      - ./data/custom-files:/customFiles/
      - ./data/logs:/logs/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.stirling-pdf.rule=Host(`${SERVICE_SUBDOMAIN:-pdfs}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.stirling-pdf.tls=true"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
    restart: unless-stopped
