networks:
  proxy:
    external: true

services:
  nexterm:
    image: germannewsmaker/nexterm:1.2.0-BETA@sha256:89afcecb66d87aed3ff7df1c958683de062eea2ed969fcd75fef0faff099634a
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexterm.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.nexterm.rule=Host(`${SERVICE_SUBDOMAIN:-preview.remote}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.nexterm.tls=true"
      - "traefik.http.routers.nexterm.tls.certresolver=letsencrypt"
      - "traefik.http.services.nexterm.loadbalancer.server.port=6989"
    restart: unless-stopped
