networks:
  proxy:
    external: true

services:
  nexterm:
    image: germannewsmaker/nexterm:latest
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nexterm-prefix.stripprefix.prefixes=/preview"
      - "traefik.http.routers.nexterm.middlewares=crowdsec-traefik-bouncer,auth,nexterm-prefix"
      - "traefik.http.routers.nexterm.rule=Host(`remote.${SERVICES_BASE_DOMAIN}`) && PathPrefix(`/preview`)"
      - "traefik.http.routers.nexterm.tls=true"
      - "traefik.http.services.nexterm.loadbalancer.server.port=6989"
    restart: unless-stopped
