networks:
  proxy:
    external: true

services:
  open-speed-test:
    image: openspeedtest/latest:v2.0.6@sha256:a6a7e3b3e9e93cfe7b9b2eb49c60b2a93644149a0a600845d4df57148b193ff6
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-speed-test.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.open-speed-test.rule=Host(`${SERVICE_SUBDOMAIN:-speed}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.open-speed-test.tls=true"
      - "traefik.http.services.open-speed-test.loadbalancer.server.port=3000"
    restart: unless-stopped
