#!/bin/env bash

get-terraform-vars() {
    touch terraform.tfvars

    grep '^variable' variable.tf | while read -r LINE; do
        VAR=$(echo "$LINE" | awk '{print $2}')
        DEFAULT=$(echo var."$VAR" | tofu console)
        DEFAULT_STRIPPED=$(echo "$DEFAULT" | xargs)

        if ! grep -q "$VAR" terraform.tfvars; then
            INPUT=
            while [[ -z "${INPUT:-}" ]]; do
                INPUT="$(gum input --header "Enter a value for $VAR" --placeholder "$DEFAULT_STRIPPED" </dev/tty)"
            done

            if [[ $DEFAULT = '"'*'"' ]]; then
                INPUT="\"$INPUT\""
            fi

            echo "$VAR = $INPUT" >>terraform.tfvars
        fi
    done
}
