networks:
  proxy:
    external: true
  homepage:
    name: homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York    # optional: set desired timezone
      - HOMEPAGE_ALLOWED_HOSTS=${SERVICE_SUBDOMAIN:-dash}.${SERVICES_BASE_DOMAIN}
    volumes:
      - ./data/config:/app/config
      - ./data/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.homepage.rule=Host(`${SERVICE_SUBDOMAIN:-dash}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - proxy
      - homepage

  homepage-docker-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      - homepage
