#!/bin/bash
set -euo pipefail

PHOTON_VERSION="$(cat source/.last_release)"

docker build source --build-arg PHOTON_VERSION="$PHOTON_VERSION" --tag git."${SERVICES_BASE_DOMAIN}"/"$GITEA_USER"/photon:"$PHOTON_VERSION"

docker tag git."${SERVICES_BASE_DOMAIN}"/"$GITEA_USER"/photon:"$PHOTON_VERSION" git."${SERVICES_BASE_DOMAIN}"/"$GITEA_USER"/photon:latest

docker push -a git."${SERVICES_BASE_DOMAIN}"/"$GITEA_USER"/photon
