#!/bin/bash

if ! kubectl get namespaces | grep -q argocd; then
    kubectl create namespace argocd
fi
kubectl apply -n argocd -f <(curl -sSL https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml | yq 'select(.spec.template.spec.containers[].name == "argocd-server").spec.template.spec.containers[].args += "--insecure"')
