site_name: !ENV SITE_NAME
site_url: !ENV SITE_URL

repo_url: !ENV REPO_URL
extra:
  homepage: !ENV HOMEPAGE
  social:
    - icon: fontawesome/brands/github
      link: !ENV GITHUB_LINK
    - icon: fontawesome/brands/mastodon
      link: !ENV MASTODON_LINK

theme:
  name: "material"
  logo: !ENV LOGO
  favicon: !ENV FAVICON
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

nav:
  - Home: index.md

plugins:
  - search
  - meta
  - offline
  - privacy
  - social
  - tags
