networks:
  proxy:
    external: true

services:
  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:1.2.0@sha256:c235b874fe1a94491b0fd1ff83a7c80eb2eab42ae60bd728bb036afc2a5ad38a
    networks:
      - proxy
    volumes:
      - ./data:/app
    environment:
      PUID: 1000
      PGID: 1000
      MASTERPASS: ${MASTERPASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drizzle-gateway.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.drizzle-gateway.rule=Host(`${SERVICE_SUBDOMAIN:-orm}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.drizzle-gateway.tls=true"
      - "traefik.http.services.drizzle-gateway.loadbalancer.server.port=4983"
    restart: unless-stopped
