networks:
  proxy:
    external: true

services:
  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:1.2.0@sha256:f05486f65e0b77bdc455f8d191362bbb68496f906d1718b9a2cf561cda559a46
    networks:
      - proxy
    volumes:
      - ./data:/app
    environment:
      PUID: 1000
      PGID: 1000
      MASTERPASS: ${MASTERPASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drizzle-gateway.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.drizzle-gateway.rule=Host(`${SERVICE_SUBDOMAIN:-orm}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.drizzle-gateway.tls=true"
      - "traefik.http.services.drizzle-gateway.loadbalancer.server.port=4983"
    restart: unless-stopped
