networks:
  proxy:
    external: true

services:
  socrates:
    image: ghcr.io/dougburks/so-crates:3.0.0@sha256:3e4f777a54146aa8f8abbd40bd33bdb541d2e75c8e33b8679bb6f68dda5611e6
    networks:
      - proxy
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socrates.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.socrates.rule=Host(`${SERVICE_SUBDOMAIN:-pcap}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.socrates.tls=true"
      - "traefik.http.services.socrates.loadbalancer.server.port=8000"
    restart: unless-stopped
