networks:
  proxy:
    external: true

services:
  socrates:
    image: ghcr.io/dougburks/so-crates:4.0.0@sha256:b0d96fef2e5f65a695bfe02e7a6630099798537a88ddf56b80e30a6bd96f73ee
    networks:
      - proxy
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socrates.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.socrates.rule=Host(`${SERVICE_SUBDOMAIN:-pcap}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.socrates.tls=true"
      - "traefik.http.services.socrates.loadbalancer.server.port=8000"
    restart: unless-stopped
