networks:
  proxy:
    external: true

services:
  socrates:
    image: ghcr.io/dougburks/so-crates:1.1.1@sha256:ec6c018a1becca49b0326afb8f24ba552ad4b9c24470a6aa64a5eba0ada18f03
    networks:
      - proxy
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socrates.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.socrates.rule=Host(`${SERVICE_SUBDOMAIN:-pcap}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.socrates.tls=true"
      - "traefik.http.services.socrates.loadbalancer.server.port=8000"
    restart: unless-stopped
