networks:
  proxy:
    external: true

services:
  tesla:
    image: nginx:1.31.2@sha256:c90e4ea5905ee69515d84cd5520e11d204df06cce71a312666cebbc4b9b68267
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config/tesla.conf:/etc/nginx/conf.d/tesla.conf:ro
      - ./data/well-known:/etc/nginx/html/.well-known:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tesla.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.tesla.rule=Host(`${SERVICE_SUBDOMAIN:-tesla}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.tesla.tls=true"
      - "traefik.http.services.tesla.loadbalancer.server.port=80"
    restart: unless-stopped
