networks:
  proxy:
    external: true

services:
  tesla:
    container_name: tesla
    image: nginx:latest
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config/tesla.conf:/etc/nginx/conf.d/tesla.conf:ro
      - ./data/well-known:/etc/nginx/html/.well-known:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tesla.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.tesla.rule=Host(`tesla.conway.dev`)"
      - "traefik.http.routers.tesla.tls=true"
      - "traefik.http.routers.tesla.tls.certresolver=prod"
      - "traefik.http.services.tesla.loadbalancer.server.port=80"
    restart: unless-stopped
