networks:
  proxy:
    external: true

services:
  tesla:
    image: nginx:1.31.3@sha256:640dee81b9ada2bf929ae17c2c7e88930f244216aa6418306226ce9bdc3271e6
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config/tesla.conf:/etc/nginx/conf.d/tesla.conf:ro
      - ./data/well-known:/etc/nginx/html/.well-known:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tesla.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.tesla.rule=Host(`${SERVICE_SUBDOMAIN:-tesla}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.tesla.tls=true"
      - "traefik.http.services.tesla.loadbalancer.server.port=80"
    restart: unless-stopped
