networks:
  proxy:
    external: true

services:
  tesla:
    image: nginx:1.29.8@sha256:7f0adca1fc6c29c8dc49a2e90037a10ba20dc266baaed0988e9fb4d0d8b85ba0
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config/tesla.conf:/etc/nginx/conf.d/tesla.conf:ro
      - ./data/well-known:/etc/nginx/html/.well-known:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tesla.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.tesla.rule=Host(`${SERVICE_SUBDOMAIN:-tesla}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.tesla.tls=true"
      - "traefik.http.services.tesla.loadbalancer.server.port=80"
    restart: unless-stopped
