networks:
  proxy:
    external: true

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    volumes:
      - /mnt/nas/content/media/books:/audiobooks
      - /mnt/nas/content/media/podcasts:/podcasts
      - /mnt/nas/content/media/manga:/manga
      - ./data/config:/config
      - ./data/metadata:/metadata
    networks:
      - proxy
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audio.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.audiobookshelf.tls=true"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=prod"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
    restart: unless-stopped
