networks:
  proxy:
    external: true
  tranga:
    name: tranga

services:
    tranga-api:
      image: glax/tranga-api:latest@sha256:dd7d8fc08ee3455c5e02feea35d70ce1bf2b58b671d72e1cbd861933d91219c7
      volumes:
        - /mnt/nas/content/media/manga:/Manga
        - ./data:/usr/share/tranga-api
      restart: unless-stopped
      environment:
        - PUID=1000
        - PGID=1000
        - POSTGRES_HOST=tranga-postgres
        - POSTGRES_USER=${POSTGRES_USER:-tranga}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - proxy
        - tranga
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.tranga-api.stripprefix.prefixes=/api/"
        - "traefik.http.routers.tranga-api.middlewares=crowdsec-traefik-bouncer,auth,tranga-api"
        - "traefik.http.routers.tranga-api.rule=Host(`${SERVICE_SUBDOMAIN:-tranga}.${SERVICES_BASE_DOMAIN}`) && PathPrefix(`/api/`)"
        - "traefik.http.routers.tranga-api.tls=true"
        - "traefik.http.services.tranga-api.loadbalancer.server.port=6531"

    tranga:
      image: glax/tranga-website:latest@sha256:68c1f4ca19b90bda9ad533036d71c94c1f31567e34b93eae5a87bc3c3fc13616
      depends_on:
        - tranga-api
      restart: unless-stopped
      networks:
        - proxy
        - tranga
      environment:
        - PUID=1000
        - PGID=1000
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tranga.middlewares=crowdsec-traefik-bouncer,auth"
        - "traefik.http.routers.tranga.rule=Host(`${SERVICE_SUBDOMAIN:-tranga}.${SERVICES_BASE_DOMAIN}`)"
        - "traefik.http.routers.tranga.tls=true"
        - "traefik.http.services.tranga.loadbalancer.server.port=80"

    tranga-postgres:
      image: docker.io/library/postgres:18.3@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
      environment:
        - POSTGRES_USER=${POSTGRES_USER:-tranga}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - tranga
      volumes:
        - ./data/db:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
      restart: unless-stopped
