networks:
  proxy:
    external: true
  linkwarden:
    name: linkwarden

services:
  linkwarden-postgres:
    image: postgres:16.13-alpine3.23@sha256:20edbde7749f822887a1a022ad526fde0a47d6b2be9a8364433605cf65099416
    env_file: .env
    networks:
      - linkwarden
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.14.0@sha256:c5b9b4db571c468270cd916acebd5e6490b54393d90c1a2ccb9919a194ed7d51
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@linkwarden-postgres:5432/${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ./data/app:/data/data
    networks:
      - proxy
      - linkwarden
    depends_on:
      - linkwarden-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.linkwarden.rule=Host(`${SERVICE_SUBDOMAIN:-bookmarks}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.linkwarden.tls=true"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
