networks:
  proxy:
    external: true
  linkwarden:
    name: linkwarden

services:
  linkwarden-postgres:
    image: postgres:16-alpine
    container_name: linkwarden-postgres
    env_file: .env
    networks:
      - linkwarden
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data

  linkwarden:
    env_file: .env
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@linkwarden-postgres:5432/${POSTGRES_DB}
    restart: unless-stopped
    image: ghcr.io/linkwarden/linkwarden:latest
    volumes:
      - ./data/data:/data/data
    networks:
      - proxy
      - linkwarden
    depends_on:
      - linkwarden-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.linkwarden.rule=Host(`bookmarks.conway.dev`)"
      - "traefik.http.routers.linkwarden.tls=true"
      - "traefik.http.routers.linkwarden.tls.certresolver=prod"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
