networks:
  proxy:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:2026.7.0@sha256:5e49861633763e8933475477c20bae6039ed47f32c1d267a34babc347f28f0df
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
