networks:
  proxy:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.2@sha256:e9bcb2ef08d25632ff74344e73a025f4f4bf12718335b196fa0e670cacace8c5
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
