networks:
  proxy:
    external: true

services:
  olivetin:
    image: jamesread/olivetin:3000.17.0@sha256:abe367efc660c8e5d755a61d7150a31da143798741f7f75128d562c70d744e2a
    networks:
      - proxy
    volumes:
      - ./config/:/config/ # replace host path or volume as needed
      - ./data/ssh/:/home/olivetin/.ssh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olivetin.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.olivetin.rule=Host(`${SERVICE_SUBDOMAIN:-run}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.olivetin.tls=true"
      - "traefik.http.services.olivetin.loadbalancer.server.port=1337"
    restart: unless-stopped
