networks:
  proxy:
    external: true

services:
  olivetin:
    image: jamesread/olivetin:3000.20.0@sha256:f3066e207efd35ab8f9ffd71cf7e2abb78d2b1edaf77ea924113bdbe6ef4f989
    networks:
      - proxy
    volumes:
      - ./config/:/config/ # replace host path or volume as needed
      - ./data/ssh/:/home/olivetin/.ssh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olivetin.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.olivetin.rule=Host(`${SERVICE_SUBDOMAIN:-run}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.olivetin.tls=true"
      - "traefik.http.services.olivetin.loadbalancer.server.port=1337"
    restart: unless-stopped
