networks:
  proxy:
    external: true
  healthchecks:
    name: healthchecks

services:
  db:
    image: postgres:18.3@sha256:059fa0289cc5a184034e05a1f4f6d6fd79f69dc718b8b04ab60b6b469eed411e
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks:
      - healthchecks
    restart: unless-stopped

  web:
    image: healthchecks/healthchecks:v4.1.1@sha256:121ba627216f04ef56b6f4c4e1e2028c9ebb8457bd2b6ede797582a80769841d
    env_file: .env
    networks:
      - proxy
      - healthchecks
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthchecks.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.healthchecks.rule=Host(`${SERVICE_SUBDOMAIN:-health}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.healthchecks.tls=true"
      - "traefik.http.services.healthchecks.loadbalancer.server.port=8000"
    restart: unless-stopped
