networks:
  proxy:
    external: true

services:
  slskd:
    image: slskd/slskd:0.24.5@sha256:17ef977563be206f3b5932080b1e23883b2cb39dc9010640f6f39b4eaec887e3
    networks:
      - proxy
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    user: 1000:1000
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./data/slskd.yml:/app/slskd.yml
      - ./data/app:/app/data
      - /mnt/nas/content/incomplete:/data/incomplete
      - /mnt/nas/content/downloads:/data/downloads
      - /mnt/nas/content/media/music:/shares:ro
    restart: unless-stopped
