networks:
  proxy:
    external: true

services:
  slskd:
    image: slskd/slskd:0.26.0@sha256:ecd4026d4f8fb504e2cc55323efa2c1f5b56d20d3686b018249cc36b48ea17a6
    networks:
      - proxy
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    user: 1000:1000
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./data/slskd.yml:/app/slskd.yml
      - ./data/app:/app/data
      - /mnt/nas/content/incomplete:/data/incomplete
      - /mnt/nas/content/downloads:/data/downloads
      - /mnt/nas/content/media/music:/shares:ro
    restart: unless-stopped
