networks:
  proxy:
    external: true

services:
  slskd:
    image: slskd/slskd:0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3
    networks:
      - proxy
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    user: 1000:1000
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./data/slskd.yml:/app/slskd.yml
      - ./data/app:/app/data
      - /mnt/nas/content/incomplete:/data/incomplete
      - /mnt/nas/content/downloads:/data/downloads
      - /mnt/nas/content/media/music:/shares:ro
    restart: unless-stopped
