services:
    periphery:
        image: ghcr.io/moghtech/komodo-periphery:2.2.0@sha256:7fb1a4807d125ce036a17d37c940b4001402afcaf342a2c720c98d096b1b54da
        init: true
        restart: unless-stopped
        logging:
            driver: local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/proc
            - ./data/app:/etc/komodo
            - ./data/keys:/config/keys
            - ${DOCKER_STACK_DIR}:${DOCKER_STACK_DIR}:ro
        environment:
            PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
            PERIPHERY_CORE_ADDRESS: deploy.${SERVICES_BASE_DOMAIN}
            PERIPHERY_CONNECT_AS: ${HOSTNAME}
            PERIPHERY_ONBOARDING_KEY: ${PERIPHERY_ONBOARDING_KEY}
        labels:
            - "komodo.skip=true"
