networks:
  proxy:
    external: true
  invoice-ninja:
    name: invoice-ninja

services:
  invoice-ninja:
    image: invoiceninja/invoiceninja-debian:5.13.30@sha256:3e8649be15e9fb7d76626d6ab06cd46dabc8dcba5910d77f7f7f8c885e367cac
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data/app/public:/var/www/html/public
      - ./data/app/storage:/var/www/html/storage
    environment:
      - PUID=1000
      - PGID=1000
    depends_on:
      invoice-ninja-mysql:
        condition: service_healthy
      invoice-ninja-redis:
        condition: service_healthy
    networks:
      - invoice-ninja

  invoice-ninja-nginx:
    image: nginx:1.31.3@sha256:8541484afbc9c8a5a8a99b379568ebbc957f658583ec9448fc43104229c03cf8
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./data/app/public:/var/www/html/public:ro
      - ./data/app/storage:/var/www/html/storage:ro
    depends_on:
      - invoice-ninja
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - proxy
      - invoice-ninja
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoice-ninja.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.invoice-ninja.rule=Host(`${SERVICE_SUBDOMAIN:-invoices}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.invoice-ninja.tls=true"
      - "traefik.http.services.invoice-ninja.loadbalancer.server.port=80"

  invoice-ninja-mysql:
    image: mysql:8.4.11@sha256:b3b90af2a6552ae30c266fdb7d5dd55f3afb72404bb78d37fe8a23eb857fd3fb
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - invoice-ninja
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]

  invoice-ninja-redis:
    image: redis:8.10.0-alpine@sha256:978f0e01593e65eed801f2402944efcd936d43b5027e4908a7897baf88ed6241
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
        - invoice-ninja
