networks:
  proxy:
    external: true
  invoice-ninja:
    name: invoice-ninja

services:
  invoice-ninja:
    image: invoiceninja/invoiceninja-debian:5.13.44@sha256:7af1f80f2647a7da7f80167dd681e301d42724280b253a1ddc9e5d6e07f17e57
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data/app/public:/var/www/html/public
      - ./data/app/storage:/var/www/html/storage
    environment:
      - PUID=1000
      - PGID=1000
    depends_on:
      invoice-ninja-mysql:
        condition: service_healthy
      invoice-ninja-redis:
        condition: service_healthy
    networks:
      - invoice-ninja

  invoice-ninja-nginx:
    image: nginx:1.31.6@sha256:60f0d4e986561e08804f75c211dcaf7fc5455699eada29f42cbe8a0a7253dd86
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./data/app/public:/var/www/html/public:ro
      - ./data/app/storage:/var/www/html/storage:ro
    depends_on:
      - invoice-ninja
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - proxy
      - invoice-ninja
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoice-ninja.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.invoice-ninja.rule=Host(`${SERVICE_SUBDOMAIN:-invoices}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.invoice-ninja.tls=true"
      - "traefik.http.services.invoice-ninja.loadbalancer.server.port=80"

  invoice-ninja-mysql:
    image: mysql:8.4.11@sha256:6ea90827b1100f8f2ae306a539f86d2c264a26ed435a2a9f75551dd5c3aeb242
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - invoice-ninja
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]

  invoice-ninja-redis:
    image: redis:8.10.2-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
        - invoice-ninja
