networks:
  proxy:
    external: true

services:
  sabnzbd:
    image: linuxserver/sabnzbd:4.5.5@sha256:374051b90f64d107f8658dcd9b9065c28826afe14562647214f45057e119fc04
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./data/config:/config
      - /mnt/nas/content/usenet:/data/usenet
    # ports:
    #   - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.sabnzbd.rule=Host(`${SERVICE_SUBDOMAIN:-use}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
