services:
  glances:
    image: nicolargo/glances:4.5.3.2-full@sha256:2d16ab0fdba4b9f61b327f78dbb8a7e7931f4967be8e1db4d37326e4680e8433
    restart: unless-stopped
    pid: host
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/glances.conf:/glances/conf/glances.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=AMerica/New_York
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w --disable-webui"
