apiVersion: ENC[AES256_GCM,data:ndU=,iv:iV3tR5iFUXqPPlXOrN5BGAL5gxxMZpmcQ98db3pdbN4=,tag:tWQvlvDjT+apyp36OEQfjw==,type:str]
kind: ENC[AES256_GCM,data:JfQnY+R6,iv:7GkwDnS8e/XIOmCJDbMT9SeA7Z9iMiv0k3TxLYecAy4=,tag:EeZOIStWdqH6AxcldwtPxw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nhObo3ojKPZLVcgxXjCYQOKtx/g=,iv:HcMrInrXYfMnVe97CLGw0BRVIEaEVq58jef7mBcMyms=,tag:NJguiiMcUYAiDTVjRwn9Lw==,type:str]
    namespace: ENC[AES256_GCM,data:gVsDGjnwunUKd48Z,iv:dOhGBgDzJ9ht0o30plmhbPn1xsZTz9/k5oS2KzXaewA=,tag:Z8rd9R/hj3S8TTusKGWZ7g==,type:str]
type: ENC[AES256_GCM,data:kToFsNHI,iv:Y59x+xkYzvg8zjA36jY5Emh6PEmAlVzOUApo50Pg42Q=,tag:HfL+HVzILhqoSTlKONuyqA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:qUoPqIzxHSBbeLeaJkFzrBs4KnKxO4vUYO6yWer8XQRvSK0h7mHoLA==,iv:hglqPp2EDvO02lteBgI6v20vbILXLpwMIMpUww1t87c=,tag:pDlwYKenGp9R2pBvdAQSoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-03T03:02:32Z"
    mac: ENC[AES256_GCM,data:RUQgnDo7xj2HRe42TxF8rPgkts+xbltHT0qah1gNbFH/mT6rHdhupn7vpnNyBUJWpRVDyqNqG5a+Nw/ZO8Bi5qCEibKORaIXr5F5omz3JOPhZCWBc84+GRlWeYQfMYnd5CW7hocgj/D0QwsfuX/+cnjGAzoq6w2ph2ky5/1IJdo=,iv:zEuNWkVZUFxA2GZKA98Codq9JwEoEfCqRi8yzLhpASE=,tag:d+QGLqkkkNnXT0AjokdMOQ==,type:str]
    pgp:
        - created_at: "2025-02-03T03:02:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dr/hYQmFOZf4SAQdA1IU201vctRJLcs5kpdSfUdL49uxXA9566YD9jTYzJ0Mw
            uluVGaNgKQesLAZ42VEi/BEmlta1xMBrtvndIIGHyf2xwtZb3XS/PhV/kTKkaz25
            0lwBbDlHMqJlTU/hZaAIKKbwNl5906Fz848Ucro92OSwYf3oBcIqRCZTxkYywc5V
            mtMenwJPHwJdFST6wAjRNOwMKmxV+henqs+L+5X+uLvuHynrKdMuzr1iOJsAuQ==
            =Q9Zf
            -----END PGP MESSAGE-----
          fp: 185913351357BA99FDC4847EAA850592E4C1D453
    unencrypted_suffix: _unencrypted
    version: 3.9.4
