#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")"
if [[ -e .env ]]; then source .env; fi

if [[ ! -e secrets.encrypted.yaml ]]; then
    if [[ ! -e secrets.yaml ]]; then
        talosctl gen secrets
        sops encrypt --pgp "$(gpg --with-colons --list-keys "$GPG_EMAIL" | awk -F: '/^pub:.*/ { getline; print $10}')" secrets.yaml >secrets.encrypted.yaml
        rm secrets.yaml
    fi
fi

SECRETS="$(sops decrypt secrets.encrypted.yaml)"

talosctl gen config proxmox "https://$API_SERVER:6443" \
    --install-image factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.9.2 \
    --with-secrets <(echo "$SECRETS") \
    --force \
    --config-patch-control-plane @patches/vip.yaml \
    --additional-sans "$ENDPOINT"

NODES=(
    "10.0.10.100 talos-cp-00 controlplane.yaml"
    "10.0.10.101 talos-cp-01 controlplane.yaml"
    "10.0.10.102 talos-cp-02 controlplane.yaml"

    "10.0.10.150 talos-worker-00 worker.yaml"
    "10.0.10.151 talos-worker-01 worker.yaml"
    "10.0.10.152 talos-worker-02 worker.yaml"
)

for c in "${NODES[@]}"; do
    IP="$(echo "$c" | awk '{print $1}')"
    NAME="$(echo "$c" | awk '{print $2}')"
    FILE="$(echo "$c" | awk '{print $3}')"

    talosctl apply-config \
        -n "$IP" \
        -e "$IP" \
        --file "$FILE" \
        --config-patch '[{ "op": "add", "path": "/machine/network/hostname", "value": "'"$NAME"'"}]'
done

IP="$(echo "${NODES[0]}" | awk '{print $1}')"
talosctl bootstrap -n "$IP" -e "$IP"

talosctl config --talosconfig talosconfig node "$API_SERVER"
talosctl config --taloscon'fig talosconfig endpoint "$ENDPOINT"
