#!/bin/bash
set -euo pipefail

helm repo add jetstack https://charts.jetstack.io --force-update

if ! helm list -n cert-manager | grep cert-manager; then
  helm install \
    cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --set crds.enabled=true \
    --set 'extraArgs={--dns01-recursive-nameservers-only,--dns01-recursive-nameservers=8.8.8.8:53\,1.1.1.1:53}'
fi

SECRETS="$(sops decrypt --input-type yaml --output-type yaml cert-manager/secrets.encrypted)"

kubectl apply -f <(echo "$SECRETS") -f cert-manager
kubectl -n cert-manager describe deploy cert-manager | grep dns01

LATEST_METALLB="$(curl -s https://api.github.com/repos/metallb/metallb/releases/latest | jq -r '.tag_name')"

kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/"$LATEST_METALLB"/config/manifests/metallb-native.yaml
