networks:
  proxy:
    external: true
  pihole:
    name: pihole
    ipam:
      config:
        - subnet: 10.1.0.0/16

services:
  pihole:
    image: pihole/pihole:latest
    depends_on:
      - unbound
    dns:
      - "127.0.0.1"
    ports:
      - ${LOCAL_IP}:53:53/tcp
      - ${LOCAL_IP}:53:53/udp
      - ${TAILSCALE_IP}:53:53/tcp
      - ${TAILSCALE_IP}:53:53/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.middlewares=crowdsec-traefik-bouncer,pihole-redirect@file"
      - "traefik.http.routers.pihole.rule=Host(`dns2.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=prod"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    volumes:
      - ./data/data:/etc/pihole:rw
      - ./data/dnsmasq:/etc/dnsmasq.d:rw
    restart: unless-stopped
    networks:
      proxy:
      pihole:
        ipv4_address: 10.1.1.2

  unbound:
    image: mvance/unbound:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
    volumes:
      - ./data/unbound/pi-hole.conf:/opt/unbound/etc/unbound/unbound.conf.d/pi-hole.conf
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 10.1.1.3
