networks:
  proxy:
    external: true
  pihole:
    name: pihole
    ipam:
      config:
        - subnet: 10.1.0.0/16

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - unbound
    dns:
      - "127.0.0.1"
    ports:
      - 10.0.10.2:53:53/tcp
      - 10.0.10.2:53:53/udp
      - 100.90.230.2:53:53/tcp
      - 100.90.230.2:53:53/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
      - DNS1=10.1.1.3#53
      - DNS2=no
      - DNSSEC="true"
      - DNSMASQ_LISTENING=all
      - DNSMASQ_USER=root
      - FTLCONF_LOCAL_IPV4=10.0.10.2
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_TARGET=10.0.10.1
      - REV_SERVER_CIDR=10.0.0.0/8
      - WEBPASSWORD=${WEBPASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.middlewares=crowdsec-traefik-bouncer,pihole@file,pihole2@file"
      - "traefik.http.routers.pihole.rule=Host(`dns2.conway.dev`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=prod"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    volumes:
      - ./data/data:/etc/pihole:rw
      - ./data/dnsmasq:/etc/dnsmasq.d:rw
    restart: unless-stopped
    networks:
      proxy:
      pihole:
        ipv4_address: 10.1.1.2

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
    volumes:
      - ./data/unbound/pi-hole.conf:/opt/unbound/etc/unbound/unbound.conf.d/pi-hole.conf
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 10.1.1.3
