networks:
  proxy:
    external: true
  teslamate:
    name: teslamate

services:
  teslamate:
    image: teslamate/teslamate:3.0.0@sha256:6569026b73bd657455bbec05965d07fa30b6d4d70eaab0bd5b343231c0429167
    networks:
      - teslamate
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${POSTGRES_PASSWORD}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-postgres
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USERNAME=mqtt
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    volumes:
      - ./data/import:/opt/app/import
    cap_drop:
      - all
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teslamate.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.teslamate.rule=Host(`${SERVICE_SUBDOMAIN:-car}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.teslamate.tls=true"
      - "traefik.http.services.teslamate.loadbalancer.server.port=4000"
    restart: unless-stopped

  teslamate-postgres:
    image: postgres:18.3-trixie@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=teslamate
    networks:
      - teslamate
    volumes:
      - ./data/db:/var/lib/postgresql

  teslamate-grafana:
    image: teslamate/grafana:3.0.0@sha256:e02d1f036dd10771ea04db2bafc483067a9dbb874d0b5137dda5a6fe539b77dc
    restart: unless-stopped
    user: 0:0
    networks:
      - teslamate
      - proxy
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${POSTGRES_PASSWORD}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-postgres
    volumes:
      - ./data/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teslamate-grafana.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.teslamate-grafana.rule=Host(`${SERVICE2_SUBDOMAIN:-data.car}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.teslamate-grafana.tls=true"
      - "traefik.http.routers.teslamate-grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.teslamate-grafana.loadbalancer.server.port=3000"
