#!/bin/bash
set -euo pipefail

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
    export DEBUG_MODE
fi

cd "$SCRIPT_DIR/infrastructure/talos"

if [[ ! -e terraform.tfstate ]]; then
    tofu init
    tofu apply -auto-approve
fi

CP_NODES="$(tofu output -json cp-nodes | jq '.[]' | sed -e 's/^"//' -e 's/"$//')"
WORKER_NODES="$(tofu output -json worker-nodes | jq '.[]' | sed -e 's/^"//' -e 's/"$//')"

cd "$SCRIPT_DIR/kubernetes/talos"

if ([[ -e talosconfig ]] || ! gum confirm "A talos cluster has not been configured, would you like to configure it now?") && [[ -z "${BOOTSTRAP_TALOS:-}" ]]; then
    exit 0
fi

if [[ ! -e secrets.yaml ]]; then
    talosctl gen secrets
fi

sops encrypt --pgp "$GPG_KEY" secrets.yaml > secrets.encrypted.yaml
rm secrets.yaml

SECRETS="$(sops decrypt secrets.encrypted.yaml)"

talosctl gen config proxmox "https://$TALOS_API_SERVER:6443" \
    --install-image factory.talos.dev/metal-installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.10.0 \
    --install-disk '/dev/vda' \
    --with-secrets <(echo "$SECRETS") \
    --force \
    --config-patch-control-plane @patches/vip.yaml \
    --additional-sans "$TALOS_ENDPOINT"

talosctl config --talosconfig talosconfig node "$TALOS_API_SERVER"
talosctl config --talosconfig talosconfig endpoint "$TALOS_ENDPOINT"
talosctl config merge talosconfig

while read -r c; do
    NAME="$(echo "$c" | awk '{print $1}')"
    IP="$(echo "$c" | awk '{print $2}')"

    talosctl apply-config --insecure \
        -n "$IP" \
        -e "$IP" \
        --file "controlplane.yaml" \
        --config-patch '[{ "op": "add", "path": "/machine/network/hostname", "value": "'"$NAME"'"}]'
done < <(echo "$CP_NODES")

while read -r c; do
    NAME="$(echo "$c" | awk '{print $1}')"
    IP="$(echo "$c" | awk '{print $2}')"

    talosctl apply-config --insecure \
        -n "$IP" \
        -e "$IP" \
        --file "controlplane.yaml" \
        --config-patch '[{ "op": "add", "path": "/machine/network/hostname", "value": "'"$NAME"'"}]'
done < <(echo "$WORKER_NODES")

echo "Waiting 1 minute for reboots..."
sleep 60

IP="$(echo "$CP_NODES" | xargs | awk '{print $2}')"
talosctl bootstrap -n "$IP" -e "$IP" --talosconfig=./talosconfig

talosctl kubeconfig -n "$IP" -e "$IP"
