#!/bin/bash
set -euo pipefail

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
    export DEBUG_MODE
fi

if [[ -z "${K8S_MANIFEST_DIR:-}" ]]; then
    K8S_MANIFEST_DIR="$(gum input --header "Where would you like to install the kubernetes manifests?" --placeholder "$HOME/Kubernetes")"
    export K8S_MANIFEST_DIR="${K8S_MANIFEST_DIR:-$HOME/Kubernetes}"

    echo "Kubernetes manifests will be installed in $K8S_MANIFEST_DIR"
    mkdir -p "$K8S_MANIFEST_DIR"

    if ! grep -q 'K8S_MANIFEST_DIR' "$HOME/.$(basename "$SHELL")rc"; then
        echo >>"$HOME"/."$(basename "$SHELL")"rc
        echo "export K8S_MANIFEST_DIR=\"$K8S_MANIFEST_DIR\"" >>"$HOME"/."$(basename "$SHELL")"rc
    fi
fi

cd "$SCRIPT_DIR/kubernetes/manifests"

K8S_APPS="$(
    for APP in *; do
        echo "$APP"
    done
)"

PRESELECTED_K8S_APPS="$(
    for APP in *; do
        if [[ -e "$K8S_MANIFEST_DIR/$APP" ]]; then
            echo "$APP"
        elif [[ "$APP" == "cert-manager" || "$APP" == "meatallb" || "$APP" == "traefik" ]]; then
            echo "$APP"
        fi
    done | xargs | sed "s/ /,/g"
)"

echo $PRESELECTED_K8S_APPS
SELECTED_K8S_APPS="$(
    gum choose $K8S_APPS \
        --selected "$PRESELECTED_K8S_APPS" \
        --header 'Which kubernetes applications would you like to import? (Press escape to quit. Submitting without selecting anything will run the rest of the script)' \
        --no-limit
)"

for APP in $SELECTED_K8S_APPS; do
    gum spin --title "Copying $APP config..." -- rsync -hruvz --progress --stats "$APP/" "$K8S_MANIFEST_DIR/$APP"
done

if [[ -n "$SELECTED_K8S_APPS" ]]; then
    gum spin --title "Applying manifests..." -- apply-manifests
    echo "Kubernetes manifests applied"
fi
