#!/bin/bash
set -euo pipefail

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
    export DEBUG_MODE
fi

cd "$SCRIPT_DIR/infrastructure/talos"

if [[ -z "${BOOTSTRAP_TALOS:-}" ]]; then
    if command -v talosctl &>/dev/null &&
        talosctl config contexts | grep -q "$TALOS_CONTEXT_NAME" &>/dev/null ||
        ! gum confirm "A talos cluster has not been configured, would you like to configure it now?"; then
        exit 0
    fi
fi

if ! command -v talosctl &>/dev/null; then
    gum spin --title 'Installing talosctl' -- bash -c 'curl -sL https://talos.dev/install | sh'
fi

if ! command -v tofu &>/dev/null; then
    curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh | sh -s -- --install-method standalone
fi

if [[ ! -e terraform.tfstate ]]; then
    tofu init
fi

get-vars terraform

export PROXMOX_HOST=$(echo var.pm_api_host | tofu console | xargs)
export PROXMOX_USER=$(echo var.pm_user | tofu console | xargs)
export PROXMOX_TOKEN_ID=$(echo var.pm_api_token_id | tofu console | xargs)
export PROXMOX_TOKEN_SECRET=$(echo var.pm_api_token_secret | tofu console | xargs)
export PROXMOX_ISO_ID=$(echo var.pm_talos_iso_id | tofu console | xargs)
export PROXMOX_STORAGE_ID=$(echo "$PROXMOX_ISO_ID" | cut -d ':' -f 1)

function download-talos-iso() {
    until curl -sSL -H "Authorization: PVEAPIToken=$PROXMOX_USER!$PROXMOX_TOKEN_ID=$PROXMOX_TOKEN_SECRET" $PROXMOX_HOST/api2/json/nodes/pve/storage/"$PROXMOX_STORAGE_ID"/content | grep -q "$PROXMOX_ISO_ID"; do
        curl -sSL -H "Authorization: PVEAPIToken=$PROXMOX_USER!$PROXMOX_TOKEN_ID=$PROXMOX_TOKEN_SECRET" $PROXMOX_HOST/api2/json/nodes/pve/storage/"$PROXMOX_STORAGE_ID"/download-url \
            -d content=iso \
            -d filename="talos-$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' terraform.tfvars).iso" \
            -d url="https://factory.talos.dev/image/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515/v$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' terraform.tfvars)/metal-amd64.iso"
    done
}

export -f download-talos-iso

gum spin --title "Downloading talos ISO" -- bash -c download-talos-iso
gum spin --title "Provisioning talos VMs" -- tofu apply -auto-approve

CP_NODES="$(tofu output -json cp-nodes | jq '.[]' | sed -e 's/^"//' -e 's/"$//')"
WORKER_NODES="$(tofu output -json worker-nodes | jq '.[]' | sed -e 's/^"//' -e 's/"$//')"

(
    cd patches
    get-vars env
)
source patches/.env

rm -f taloconfig

talosctl gen config "$TALOS_CONTEXT_NAME" "https://$TALOS_API_SERVER:6443" \
    --install-image factory.talos.dev/metal-installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v"$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' terraform.tfvars)" \
    --install-disk '/dev/vda' \
    --with-secrets <(talosctl gen secrets -o -) \
    --force \
    --config-patch-control-plane @<(cat patches/vip.yaml | envsubst) \
    --additional-sans "$TALOS_API_SERVER,$TALOS_ENDPOINT"

talosctl --talosconfig=talosconfig config context "$TALOS_CONTEXT_NAME"
talosctl --talosconfig=talosconfig config node "$TALOS_API_SERVER"
talosctl --talosconfig=talosconfig config endpoint "$TALOS_ENDPOINT"

while read -r NODE; do
    export NAME="$(echo "$NODE" | awk '{print $1}')"
    export IP="$(echo "$NODE" | awk '{print $2}')"

    until nc -z "$IP" 50000; do
        sleep 5
    done

    talosctl --talosconfig=talosconfig apply-config --insecure \
        -n "$IP" \
        -e "$IP" \
        --file <(sed 's/^\(auto: stable\)/\# \1/g' controlplane.yaml && echo "hostname: $NAME")
done < <(echo "$CP_NODES")

while read -r NODE; do
    export NAME="$(echo "$NODE" | awk '{print $1}')"
    export IP="$(echo "$NODE" | awk '{print $2}')"

    until nc -z "$IP" 50000; do
        sleep 5
    done

    sed -i 's/^\(auto: stable\)/\# \1/g' worker.yaml
    echo "hostname: $NAME" >>worker.yaml

    talosctl --talosconfig=talosconfig apply-config --insecure \
        -n "$IP" \
        -e "$IP" \
        --file <(sed 's/^\(auto: stable\)/\# \1/g' worker.yaml && echo "hostname: $NAME")
done < <(echo "$WORKER_NODES")

IP="$(echo "$CP_NODES" | xargs | awk '{print $2}')"

function bootstrap-cluster() {
    until nc -z "$IP" 50000; do
        sleep 5
    done

    talosctl --talosconfig=talosconfig bootstrap -n "$IP" -e "$IP"
}

function wait-for-healthy() {
    until nc -z "$IP" 50000; do
        sleep 5
    done

    until timeout 10 talosctl --talosconfig=talosconfig health -n "$IP" -e "$IP"; do
        sleep 5
    done
}

export -f bootstrap-cluster wait-for-healthy

gum spin --title "Bootstrapping talos cluster..." -- bash -c bootstrap-cluster
gum spin --title "Waiting for talos cluster to be healthy..." -- bash -c wait-for-healthy

talosctl config merge talosconfig
talosctl kubeconfig
