#!/bin/bash
set -euo pipefail

source "$SCRIPT_DIR/utils"

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
    export DEBUG_MODE
fi

if [[ -z "${BOOTSTRAP_TALOS:-}" ]]; then
    if command -v talosctl &>/dev/null &&
        talosctl config contexts | grep -q "$TALOS_CONTEXT_NAME" &>/dev/null ||
        ! gum confirm "A talos cluster has not been configured, would you like to configure it now?"; then
        exit 0
    fi
fi

if ! command -v talosctl &>/dev/null; then
    gum spin --title 'Installing talosctl' -- bash -c 'curl -sL https://talos.dev/install | sh'
fi

cd "$SCRIPT_DIR/infrastructure/talos"

if ! command -v tofu &>/dev/null; then
    curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh | sh -s -- --install-method standalone
fi

if [[ ! -e terraform.tfstate ]]; then
    tofu init
fi

get-terraform-vars
gum spin --title "Provisioning talos VMs" -- tofu apply -auto-approve

CP_NODES="$(tofu output -json cp-nodes | jq '.[]' | sed -e 's/^"//' -e 's/"$//')"
WORKER_NODES="$(tofu output -json worker-nodes | jq '.[]' | sed -e 's/^"//' -e 's/"$//')"

if [[ ! -e secrets.yaml ]]; then
    sops encrypt <(talosctl gen secrets -o /dev/stdout --force) >secrets.encrypted.yaml
fi

TMP_FILE=$(mktemp)
get-env-vars patches/env.example >>patches/.env
source patches/.env
cat patches/vip.yaml | envsubst >"$TMP_FILE"

talosctl gen config "$TALOS_CONTEXT_NAME" "https://$TALOS_API_SERVER:6443" \
    --install-image factory.talos.dev/metal-installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v"$(grep -o 'iso/talos-.*' terraform.tfvars | sed 's/talos-//g' | sed 's,\.\?iso/\?,,g' | tr -d '"')" \
    --install-disk '/dev/vda' \
    --with-secrets <(sops decrypt secrets.encrypted.yaml) \
    --force \
    --config-patch-control-plane "@$TMP_FILE" \
    --additional-sans "$TALOS_API_SERVER,$TALOS_ENDPOINT"

rm "$TMP_FILE"

while read -r NODE; do
    NAME="$(echo "$NODE" | awk '{print $1}')"
    IP="$(echo "$NODE" | awk '{print $2}')"

    talosctl apply-config --insecure \
        -n "$IP" \
        -e "$IP" \
        --file "controlplane.yaml" \
        --config-patch '[{ "op": "add", "path": "/machine/network/hostname", "value": "'"$NAME"'"}]'
done < <(echo "$CP_NODES")

while read -r NODE; do
    NAME="$(echo "$NODE" | awk '{print $1}')"
    IP="$(echo "$NODE" | awk '{print $2}')"

    talosctl apply-config --insecure \
        -n "$IP" \
        -e "$IP" \
        --file "worker.yaml" \
        --config-patch '[{ "op": "add", "path": "/machine/network/hostname", "value": "'"$NAME"'"}]'
done < <(echo "$WORKER_NODES")

SERVERS=""
while read -r NODE; do
    IP="$(echo "$NODE" | awk '{print $2}')"
    SERVERS+=', { "address": "'"$IP:50000"'" }'
done < <(echo "$CP_NODES")

(
    cd "$DOCKER_STACK_DIR/traefik" || exit 0
    if [[ -e data/config.yml ]]; then
        yq -i ".tcp.services.talos.loadBalancer.servers = [ $(echo "$SERVERS" | cut -d ' ' -f 2-) ]" data/config.yml
        docker compose restart
    fi
)

talosctl config --talosconfig talosconfig node "$TALOS_API_SERVER"
talosctl config --talosconfig talosconfig endpoint "$TALOS_ENDPOINT"
talosctl config merge talosconfig
talosctl config context "$TALOS_CONTEXT_NAME"

IP="$(echo "$CP_NODES" | xargs | awk '{print $2}')"

function bootstrap-cluster() {
    until talosctl bootstrap -n "$IP" -e "$IP" --talosconfig=./talosconfig; do
        sleep 5
    done
}

export -f bootstrap-cluster

gum spin --title "Bootstrapping talos cluster..." -- bash -c bootstrap-cluster
gum spin --title "Waiting for talos cluster to be healthy..." -- talosctl health -n "$IP" -e "$IP"

talosctl kubeconfig -n "$IP" -e "$IP"
