#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
fi

cd "$SCRIPT_DIR/docker/compose"

if ! command -v docker &>/dev/null; then
    if [[ -n "${INSTALL_DEPENDENCIES:-}" ]] || gum confirm "Docker is not installed, would you like to install it?"; then
        curl -fsSL https://get.docker.com | sh
    fi
fi

echo "Docker stacks will be installed in $DOCKER_STACK_DIR"
mkdir -p "$DOCKER_STACK_DIR"

DOCKER_APPS="$(
    for APP in *; do
        echo "$APP"
    done
)"

if [[ -z ${PRESELECTED_DOCKER_APPS:-} ]]; then
    PRESELECTED_DOCKER_APPS="$(
        for APP in *; do
            if [[ -e "$DOCKER_STACK_DIR/$APP" ]]; then
                echo "$APP"
            fi
        done | xargs | sed "s/ /,/g"
    )"
fi

SELECTED_DOCKER_APPS="$(
    gum choose $DOCKER_APPS \
        --header 'Which docker applications would you like to import? (Press escape to quit. Submitting without selecting anything will run the rest of the script)' \
        --no-limit \
        --selected "$PRESELECTED_DOCKER_APPS"
)"

for APP in $SELECTED_DOCKER_APPS; do
    gum spin --title "Copying $APP config..." -- rsync -abhruvz --backup-dir ".rsync-backup" --progress --stats "$APP/" "$DOCKER_STACK_DIR/$APP"
    (cd "$DOCKER_STACK_DIR/$APP" && get-vars env)
done

if [[ -n "$SELECTED_DOCKER_APPS" ]]; then
    gum spin --title "Starting containers..." -- start-containers ${SELECTED_DOCKER_APPS//,/ }
    echo "Docker containers started"
fi
