networks:
  proxy:
    external: true

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - proxy
    user: 1000:1000
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.middlewares=crowdsec-traefik-bouncer,auth
      - traefik.http.routers.prometheus.rule=Host(`prometheus.conway.dev`)
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=prod
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
    restart: unless-stopped
