networks:
  proxy:
    external: true

services:
  lidarr:
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - TZ=America/New_York # Specify a timezone to use
      - UMASK_SET=022 # permissions created
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
    volumes:
      - /mnt/nas/content:/data # Location of all your media
      - ./data/config:/config # Contains all relevant configuration files.
      - ./data/custom-services.d:/custom-services.d
      - ./data/custom-cont-init.d:/custom-cont-init.d
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.lidarr.rule=Host(`music.download.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.routers.lidarr.tls.certresolver=prod"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
