networks:
  proxy:
    external: true

services:
  app:
    image: learnedmachine/speakr:0.10.3-alpha@sha256:435eae6fe0899a6597101550405a7ccd30d917cdb1115c0956c05366458a3c12
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    networks:
        - proxy
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/instance:/data/instance
      - ./data/exports:/data/exports
      - ./data/auto-process:/data/auto-process
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speakr.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.speakr.rule=Host(`${SERVICE_SUBDOMAIN:-transcriptions}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.speakr.tls=true"
      - "traefik.http.services.speakr.loadbalancer.server.port=8899"
