networks:
  proxy:
    external: true

services:
  app:
    image: learnedmachine/speakr:0.9.4-alpha@sha256:5d0906ec5e6ae2e3173e75ffc4e75efb4e2c87c765dab025fc287b809c52d044
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    networks:
        - proxy
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/instance:/data/instance
      - ./data/exports:/data/exports
      - ./data/auto-process:/data/auto-process
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speakr.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.speakr.rule=Host(`${SERVICE_SUBDOMAIN:-transcriptions}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.speakr.tls=true"
      - "traefik.http.services.speakr.loadbalancer.server.port=8899"
