networks:
  proxy:
    external: true

services:
  app:
    image: learnedmachine/speakr:0.10.9-alpha@sha256:c716323cc64a1a2ff2d233caa60875ef328b8e1053bae7b9fab6908cd4baa629
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    networks:
        - proxy
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/instance:/data/instance
      - ./data/exports:/data/exports
      - ./data/auto-process:/data/auto-process
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speakr.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.speakr.rule=Host(`${SERVICE_SUBDOMAIN:-transcriptions}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.speakr.tls=true"
      - "traefik.http.services.speakr.loadbalancer.server.port=8899"
