networks:
  proxy:
    external: true
  atuin:
    name: atuin

services:
  atuin:
    image: ghcr.io/atuinsh/atuin:18.13.6@sha256:9bde3fe6b1633c357cb19c07ea49bb9834720e8ff42d04b39ad7865155581150
    command: start
    networks:
      - atuin
      - proxy
    volumes:
      - ./config:/config
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      ATUIN_HOST: "0.0.0.0"
      ATUIN_PORT: 8888
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://atuin:${POSTGRES_PASSWORD}@atuin-postgres/atuin
      RUST_LOG: info,atuin_server=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atuin.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.atuin.rule=Host(`${SERVICE_SUBDOMAIN:-commands}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.atuin.tls=true"
      - "traefik.http.services.atuin.loadbalancer.server.port=8888"

  atuin-postgres:
    image: postgres:14.22@sha256:ae46a8452f2c137766c9d4a62f4fe60166355ff8b00512e6c48692dbf1eed3d5
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    networks:
      - atuin
    environment:
      POSTGRES_USER: atuin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: atuin
