services:
    renovate:
        image: renovate/renovate:43.279.0@sha256:12ff9ccbded485ab4187f0b56713ca3514fd5802e347441236a9153efa033aeb
        environment:
          - LOG_LEVEL=debug
          - RENOVATE_CONFIG_FILE=/config.js
          - RENOVATE_TOKEN=$RENOVATE_TOKEN
          - RENOVATE_REPOSITORIES=$RENOVATE_REPOSITORIES
          - SERVICES_BASE_DOMAIN=$SERVICES_BASE_DOMAIN
        volumes:
          - ./config/config.js:/config.js
