services:
    renovate:
        image: renovate/renovate:43.280.2@sha256:04d242dbd09e08e55687c17eda8956eb03a464ace0d6ca199fced49755fbfb0a
        environment:
          - LOG_LEVEL=debug
          - RENOVATE_CONFIG_FILE=/config.js
          - RENOVATE_TOKEN=$RENOVATE_TOKEN
          - RENOVATE_REPOSITORIES=$RENOVATE_REPOSITORIES
          - SERVICES_BASE_DOMAIN=$SERVICES_BASE_DOMAIN
        volumes:
          - ./config/config.js:/config.js
