services:
    renovate:
        image: renovate/renovate:44.6.0@sha256:82c8dbd86d8c96c44e0064e2dc5966848a4ffb497fce0e96b2a360f507b85778
        environment:
          - LOG_LEVEL=debug
          - RENOVATE_CONFIG_FILE=/config.js
          - RENOVATE_TOKEN=$RENOVATE_TOKEN
          - RENOVATE_REPOSITORIES=$RENOVATE_REPOSITORIES
          - SERVICES_BASE_DOMAIN=$SERVICES_BASE_DOMAIN
        volumes:
          - ./config/config.js:/config.js
