
networks:
  proxy:
    external: true

services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York # Specify a timezone to use
      - UMASK_SET=022 # permissions created
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
    volumes:
      - /mnt/nas/content:/data # Location of all your media
      - ./data:/config # Contains all relevant configuration files.
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.prowlarr.rule=Host(`indexers.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=prod"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
