networks:
  proxy:
    external: true

services:
  nginx:
    image: nginx:1.31.2@sha256:c90e4ea5905ee69515d84cd5520e11d204df06cce71a312666cebbc4b9b68267
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.nginx.rule=Host(`${SERVICE_SUBDOMAIN:-nginx}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    restart: unless-stopped
