networks:
  proxy:
    external: true

services:
  nginx:
    image: nginx:1.31.6@sha256:908dc23e643a1447dbfb2e189ed268bfde6a51a5bf9a34d3dd3440a24f58ccf7
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.nginx.rule=Host(`${SERVICE_SUBDOMAIN:-nginx}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    restart: unless-stopped
