networks:
  proxy:
    external: true

services:
  nginx:
    image: nginx:1.31.2@sha256:ec4ed8b5299e5e90694af7750eb6dffd2627317d30544d056b0371f8082f7bce
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.nginx.rule=Host(`${SERVICE_SUBDOMAIN:-nginx}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    restart: unless-stopped
