networks:
  proxy:
    external: true

services:
  nginx:
    image: nginx:latest
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.nginx.rule=Host(`nginx.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    restart: unless-stopped
