networks:
  proxy:
    external: true
  gitea:
    name: gitea

services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1.12.1@sha256:85361da4c2f259df6e0675c54574c991ae2601922cb56c4d0419fd3e15ceb139
    restart: unless-stopped
    networks:
      - proxy
      - gitea
    ports:
      - 2222:2222
    volumes:
      - ./data/gist:/opengist
      - ./data/gist-config.yml:/config.yml
    environment:
      UID: 1000
      GID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opengist.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.opengist.rule=Host(`${SERVICE2_SUBDOMAIN:-gist}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.opengist.tls=true"
      - "traefik.http.services.opengist.loadbalancer.server.port=6157"

  gitea:
    image: gitea/gitea:1.25.5@sha256:f846d26a4fc389c5806a580a765e00bfdd1fd181e6f2060da98ea2669d914472
    ports:
      - 222:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - proxy
      - gitea
    volumes:
      - ./data/app:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.middlewares=crowdsec-traefik-bouncer"
      - "traefik.http.routers.gitea.rule=Host(`${GIT_SUBDOMAIN:-git}.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  gitea-runner:
    image: gitea/act_runner:0.3.1@sha256:c2a169c5e99864c25e32527cef3d82203225e09558773022bf3dc164a2e6d762
    restart: unless-stopped
    volumes:
      - ./data/runner/config.yaml:/config.yaml
      - ./data/runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea
    environment:
      - GITEA_INSTANCE_URL=https://${SERVICE_SUBDOMAIN:-git}.${SERVICES_BASE_DOMAIN}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=Runner
      - USER_UID=1000
      - USER_GID=1000

  gitea-postgres:
    image: postgres:18.3@sha256:059fa0289cc5a184034e05a1f4f6d6fd79f69dc718b8b04ab60b6b469eed411e
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - gitea
