networks:
  proxy:
    external: true

services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - TZ=America/New_York # Specify a timezone to use
      - UMASK_SET=022 # permissions created
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
    volumes:
      - /mnt/nas/content:/data # Location of all your media
      - ./data/config:/config # Contains all relevant configuration files.
      - ./data/custom-services.d:/custom-services.d
      - ./data/custom-cont-init.d:/custom-cont-init.d
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.middlewares=crowdsec-traefik-bouncer,auth"
      - "traefik.http.routers.radarr.rule=Host(`movies.${SERVICES_BASE_DOMAIN}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=prod"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
